name: Caching with npm

on: push

jobs:
  build:
    runs-on: windows
    
    steps:
    
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm build
